### ISSUE TITLE
JVM crash when training in parallel (EXCEPTION_ACCESS_VIOLATION + SIGSEGV)

### ISSUE THREAD

**Issue by Habitats** [deeplearning4j/libnd4j#223]
Crash happens only when training with MKL, even when utilizing only 1gb out of 60gb memory (small net). So, it does seem to be related to running out of memory, at least. 

It also only seems to happen with nets with many inputs. I only get this with my network that has 10k inputs, it never happens with the smaller nets (1000 inputs). Nets tested are RNNs and FFNs. 

FWIW by parallel i simply mean doing something like this (i.e. parallel collections, no Spark or anything):
```scala
Seq(foo, bar).par.foreach(trainNetwork)
```

https://gist.github.com/Habitats/bd4b671ef2bf0a2c76ecb01535be0a1f

**Comment by Habitats** [comment]
Seems I get a crash for the same job using OpenBLAS on unix, however, sourcing from libnd4j this time:
https://gist.github.com/Habitats/d58dab6a01e2981c44fef9f46394ecb0

**Comment by AlexDBlack** [comment]
For the latter issue: this may be due to the issue described here: https://github.com/deeplearning4j/nd4j/issues/954
OpenBLAS simply doesn't seem to be properly thread safe on GEMM, whereas MKL seems fine (at least on my machine).

**Comment by Habitats** [comment]
Taking @sadatanwer's advice and trying to limit `OMP_NUM_THREAD=1`; if I understand this correctly this will limit one OpenMP thread per worker? I.e. if I train 2 nets in parallel I'll have 2 sandboxed OpenMP threads?

**Comment by Habitats** [comment]
Update: When training RNNs in parallel I get a third error: `Segmentation fault` in the terminal, and no logs anywhere. It seems to be the same issue as https://github.com/deeplearning4j/libnd4j/issues/205.

**Comment by saudet** [comment]
Since it's behaving the same on Linux, could you try to run that in Valgrind?
https://github.com/deeplearning4j/libnd4j/wiki/Debugging-libnd4j
It will be really really REALLY slow, but if it reports any memory corruption issues, it will be easy to fix.

**Comment by Habitats** [comment]
I have very little time for field work atm (thesis deadline in 2 weeks~), so I don't want to break my builds atm (more than what's already broken):\ I can probably try with Valgrind later this week.

I ran another RNN and this time it trained and finished (12~hours) without problems ... Weird.

**Comment by treo** [comment]
This looks like it can be really related to https://github.com/bytedeco/javacpp/issues/103 as the crashes happen when using multiple java threads and a parallel GC. @Habitats is using `-XX:+UseConcMarkSweepGC`. 
 
I asked him to try the default GC and report back.

**Comment by Habitats** [comment]
I've been training with the default GC on 10 threads for almost 4 hours now; memory is stable and without error. 

Looks like this is indeed related to CMS GC.

**Comment by saudet** [comment]
I think I found what the issue is and a way to reproduce it consistently:
https://gist.github.com/saudet/4de601b9ef25d78b3474c997c368a870
Typical output:
```
Computing call overhead...
processLongPtr(): 12 ns
processPointer(): 14 ns
Testing crashability... (Make sure to execute with -XX:+UseConcMarkSweepGC)
processPointer()...
processLongPtr()...
[thread 9912 also had an error]
[thread 1184 also had an error]
[thread 10064 also had an error]
[thread 9068 also had an error]
#
# A fatal error has been detected by the Java Runtime Environment:
#
...
```
What happens basically is that, when we pass only the address of a temporary `Pointer` object to the JNI function, the object itself is no longer reachable, so there is a possibility for the GC, especially the concurrent one, to deallocate it.

In the case ND4J, based on the stacktrace from @Habitats, this happens when calling the `INDArray .transpose()` and `mmul()` methods here for example:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/layers/BaseOutputLayer.java#L163
A `Pointer` object is create, the data used inside some native function, and discarded immediately after.

So, I think the best thing to do would be to replace all those `long` parameters to `FloatPointer`, `DoublePointer`, etc. As shown above, the overhead is pretty negligible and it also saves us writing boilerplate code for the cast operations.
