### ISSUE TITLE
Consider support for other third-party compiler in Mac OS, or build without OpenMP?

### ISSUE THREAD

**Issue by marker68** [deeplearning4j/libnd4j#300]
As a user mentioned in GITTER channel, `clang-omp` was boneyard: https://github.com/Homebrew/homebrew-core/commit/c57e307 . I think with Mac OS, it will be good to let user choose the compiler at their own or support `clang` without OpenMP (is it possible now?). Some other choices are here: https://trac.macports.org/browser/trunk/dports/lang/gcc49/Portfile

**Comment by saudet** [comment]
Looks like we just need to install `llvm` instead?
http://discourse.brew.sh/t/there-is-no-longer-a-clang-omp-formula-for-macos-sierra/47

**Comment by crockpotveggies** [comment]
Confirmed this is affecting me on OSX Sierra right now. Looking into LLVM, going to see if it can solve my problem.

**Comment by raver119** [comment]
Before Sam introduced gcc5 as compiler there, i was using llvm. Was working fine for me on sierra. However, gcc5 works fine too.

**Comment by saudet** [comment]
Yes, we're using GCC now as required by OpenBLAS (for LAPACK written in Fortran), and as already used by libnd4j on Linux, Windows, and Android (but maybe not for long since they've deprecated GCC there). This will allow us to use more advanced features of OpenMP not supported by Clang (yet) as well as prevent compatibility issues with OpenBLAS and caused by differences between Clang and GCC.

Note that Clang is still required for CUDA, so the CUDA build still uses Clang.
