### ISSUE TITLE
CPU builds for modern architectures

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/libnd4j#422]
I think it will be nice, if we could provide binaries optimized for specific CPU architectures.
That's not the case for CUDA (we do it via archs there), but for CPU it matters. Even on my 4th gen i7 CPU performance difference is noticeable (despite we don't have any manual optimizations for cpecific architectures), on more recent cpus (especially avx512-enabled) difference will be way more significant.

So, let's make this happen somehow. I.e. as @AlexDBlack suggested - some naming convention for binaries and dynamically load library that matches CPU architecture of ***this*** machine.

@saudet @agibsonccc @AlexDBlack @shyrma ideas guys?

**Comment by saudet** [comment]
It's obviously possible to do it on the native side, like CUDA, MKL, or FFmpeg does it, but a general solution in Java would be nicer, yes. IMO, that would end up in JavaCPP to help other libraries as well:
https://github.com/bytedeco/javacpp-presets/pull/416#issuecomment-305124423

**Comment by raver119** [comment]
Yes, jcpp should be definitely in play here, since we rely on jcpp for BLAS bindings. And it would be awesome to have optimized gemm as well.

**Comment by saudet** [comment]
OpenBLAS has "dynamic arch", so it should also automatically be running optimized versions already.

**Comment by saudet** [comment]
I've added an "extension" feature to JavaCPP for this: https://github.com/bytedeco/javacpp/commit/35463a65f93b52db5522a8dc8ec281289b6ac4be

Basically, we build using an "extension" name that gets appended to the platform name, that basically appears as another platform. At runtime, JavaCPP can load using the extensions listed in annotation, something like `@Platform(extensions={"-avx512", "-avx2"})`, by trying to load them one after the other. Now we'd need to figure how to make loading of a library fail gracefully, and still let us load an alternative one, in a portable way...

**Comment by raver119** [comment]
Maybe try to inspect cpu features prior LoadLibrary call?

**Comment by saudet** [comment]
We'd need some sort of helper library for that. I've been trying to stay away from doing that in JavaCPP, not that it can't work, but in this case, for example, it would require the developer to do stuff in Java that could probably be done more easily directly in the native library, like it's done in FFmpeg, OpenBLAS, MKL, etc. But let's keep that in mind, it might be possible to provide it as an easy-to-use generic feature in JavaCPP...

The fallback solution that I'm seeing is that we put only the default artifacts (without extension) in the class path. If users want avx512, they put that in the class path. If not, when JavaCPP first tries to load say "linux-x86_64-avx512", it fails ("file not found", so that's portable) and just goes trying to load the next one in line.

**Comment by saudet** [comment]
Some work toward that with https://github.com/deeplearning4j/libnd4j/pull/554 and https://github.com/deeplearning4j/nd4j/pull/2253.
